name: Build Docker Image on Push to Main

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar pruebas
        run: pytest --maxfail=1 --disable-warnings -q        

  build-and-publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          echo "-----------------------------------------------------"
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/predictor-enfermedades          
          echo "-----------------------------------------------------"
          echo "Docker image built and pushed to $IMAGE_NAME:latest"
          echo "Docker image pushed to $IMAGE_NAME:latest"
          echo "-----------------------------------------------------"
          echo "Building Docker image..."
          echo "-----------------------------------------------------"
          docker build -t $IMAGE_NAME:latest .
          echo "-----------------------------------------------------"
          echo "Pushing Docker image to GitHub Container Registry..."
          echo "-----------------------------------------------------"
          docker push $IMAGE_NAME:latest
          